[app]
overall = { bg = "#1e1e2e" }

[mgr]
cwd = { fg = "#94e2d5" }

find_keyword = { fg = "#f9e2af", italic = true }
find_position = { fg = "#f5c2e7", bg = "reset", italic = true }

marker_copied = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_cut = { fg = "#f38ba8", bg = "#f38ba8" }
marker_marked = { fg = "#94e2d5", bg = "#94e2d5" }
marker_selected = { fg = "#89b4fa", bg = "#89b4fa" }

count_copied = { fg = "#1e1e2e", bg = "#a6e3a1" }
count_cut = { fg = "#1e1e2e", bg = "#f38ba8" }
count_selected = { fg = "#1e1e2e", bg = "#89b4fa" }

border_symbol = "│"
border_style = { fg = "#7f849c" }

[tabs]
active = { fg = "#1e1e2e", bg = "#cdd6f4", bold = true }
inactive = { fg = "#cdd6f4", bg = "#45475a" }

[mode]
normal_main = { fg = "#1e1e2e", bg = "#89b4fa", bold = true }
normal_alt = { fg = "#89b4fa", bg = "#313244" }

select_main = { fg = "#1e1e2e", bg = "#a6e3a1", bold = true }
select_alt = { fg = "#a6e3a1", bg = "#313244" }

unset_main = { fg = "#1e1e2e", bg = "#f2cdcd", bold = true }
unset_alt = { fg = "#f2cdcd", bg = "#313244" }

[indicator]
parent = { fg = "#1e1e2e", bg = "#cdd6f4" }
current = { fg = "#1e1e2e", bg = "#89b4fa" }
preview = { fg = "#1e1e2e", bg = "#cdd6f4" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#a6e3a1", bg = "#45475a" }
progress_error = { fg = "#f9e2af", bg = "#f38ba8" }

perm_type = { fg = "#89b4fa" }
perm_read = { fg = "#f9e2af" }
perm_write = { fg = "#f38ba8" }
perm_exec = { fg = "#a6e3a1" }
perm_sep = { fg = "#7f849c" }

[input]
border = { fg = "#89b4fa" }
title = {}
value = {}
selected = { reversed = true }

[pick]
border = { fg = "#89b4fa" }
active = { fg = "#f5c2e7" }
inactive = {}

[confirm]
border = { fg = "#89b4fa" }
title = { fg = "#89b4fa" }
body = {}
list = {}
btn_yes = { reversed = true }
btn_no = {}

[cmp]
border = { fg = "#89b4fa" }

[tasks]
border = { fg = "#89b4fa" }
title = {}
hovered = { fg = "#f5c2e7", bold = true }

[which]
border = { fg = "#89b4fa" }
mask = {}
cand = { fg = "#94e2d5" }
rest = { fg = "#9399b2" }
desc = { fg = "#f5c2e7" }
separator = "  "
separator_style = { fg = "#585b70" }

[help]
border = { fg = "#89b4fa" }
chord = { fg = "#94e2d5" }
action = { fg = "#9399b2" }
hovered = { bg = "#585b70", bold = true }

[notify]
title_info = { fg = "#94e2d5" }
title_warn = { fg = "#f9e2af" }
title_error = { fg = "#f38ba8" }

[filetype]
rules = [
  # Media
  { mime = "**/image/*", fg = "#f9e2af" },
  { mime = "**/{audio,video}/*", fg = "#f5c2e7" },

  # Archives
  { mime = "**/application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f38ba8" },

  # Documents
  { mime = "**/application/{pdf,doc,rtf}", fg = "#89dceb" },

  # Virtual file system
  { mime = "vfs/{absent,stale}", fg = "#45475a" },

  # Special file
  { url = "*", is = "orphan", bg = "#f38ba8" },
  { url = "*", is = "exec", fg = "#a6e3a1" },

  # Dummy file
  { url = "*", is = "dummy", bg = "#f38ba8" },
  { url = "*/", is = "dummy", bg = "#f38ba8" },

  # Fallback
  { url = "*/", fg = "#89b4fa" },
]

[spot]
border = { fg = "#89b4fa" }
title = { fg = "#89b4fa" }
tbl_cell = { fg = "#89b4fa", reversed = true }
tbl_col = { bold = true }

[icon]
dirs = [
  { name = ".config", text = "", fg = "#89b4fa" },
  { name = ".git", text = "", fg = "#89b4fa" },
  { name = ".github", text = "", fg = "#89b4fa" },
  { name = ".npm", text = "", fg = "#89b4fa" },
  { name = "Desktop", text = "", fg = "#89b4fa" },
  { name = "Development", text = "", fg = "#89b4fa" },
  { name = "Documents", text = "", fg = "#89b4fa" },
  { name = "Downloads", text = "", fg = "#89b4fa" },
  { name = "Library", text = "", fg = "#89b4fa" },
  { name = "Movies", text = "", fg = "#89b4fa" },
  { name = "Music", text = "", fg = "#89b4fa" },
  { name = "Pictures", text = "", fg = "#89b4fa" },
  { name = "Public", text = "", fg = "#89b4fa" },
  { name = "Videos", text = "", fg = "#89b4fa" },
]
conds = [
  # Special files
  { if = "orphan", text = "", fg = "#cdd6f4" },
  { if = "link", text = "", fg = "#a6adc8" },
  { if = "block", text = "", fg = "#f9e2af" },
  { if = "char", text = "", fg = "#f9e2af" },
  { if = "fifo", text = "", fg = "#f9e2af" },
  { if = "sock", text = "", fg = "#f9e2af" },
  { if = "sticky", text = "", fg = "#f9e2af" },
  { if = "dummy", text = "", fg = "#f38ba8" },

  # Fallback
  { if = "dir", text = "", fg = "#89b4fa" },
  { if = "exec", text = "", fg = "#a6e3a1" },
  { if = "!dir", text = "", fg = "#cdd6f4" },
]
